title: luis pimentel 
baseurl: "/luisp23.github.io/"

markdown: kramdown
ins_logo: "./me.png"

tracking_id: #

footer: no
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: "index"
 - name: "resume"
   link: "resume.pdf"
 - name: "contact"
   link: "contact"
