title: Luis M. Pimentel
logo: /assets/img/headshot.jpeg
description: I'm a Computer Engineering undergraduate student with an interest in robotics and research. I have experience in projects related to electronics, software development, and varied Information Technology services.
google_analytics:
theme: jekyll-theme-minimal
