title: Luis M. Pimentel
logo: /assets/img/headshot.jpeg
description: I'm a Computer Engineering undergraduate student with an interest in robotics and research. 
google_analytics:
theme: jekyll-theme-minimal
